name: dash_curved_tab_bar
description: "A customizable curved tab bar for Flutter with icon, badge, and connected content support."
homepage: https://github.com/Androidsignal/dash_curved_tabbar/blob/main/example/main.dart
issue_tracker: https://github.com/Androidsignal/dash_curved_tabbar/issues
version: 0.0.2


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
